#import "template.typ": *

#show: cardiff-poster.with(
  project-title: "Microwave Mechanical Monitoring",
  author: "Archie Webster",
  author-email: "webstera2@cardiff.ac.uk",
  school: "School of Engineering, Cardiff University, Cardiff, Wales, United Kingdom",
  supervisor: "Dr Alistair Reid",
  logo: "Cardiff_University_logo.png",
)


= Introduction
Gas Insulated Switchgear (GIS) describes equipment used in power systems where components are fully enclosed in a metal
housing and pressurised with an insulating gas, commonly sulphur hexafluoride. In comparison to air-insulated lines
(AIS), this can significantly reduce the size of substations. The draw back of GIS is the introduced complexity of
identifying and repairing faults due to the inaccessibility of the components. The second most common fault in GIS
operation is particle defects. Particles suspended in the insulating gas or adhered to the conductors can cause partial
discharge (PD) to occur; a localised electrical breakdown. Current monitoring techniques detect the ultra-high frequency
(UHF) or acoustic signals generated by PD, however, these techniques are reactive. The novel microwave mechanical
monitoring approach discussed in this project aims to detect particles before they lead to PD.= Structure of GIS The GIS
studied for this project are busbars, a high-voltage (HV) inner conductor surrounded by insulating gas, completely
enclosed in a cylindrical metal shell. Regularly spaced along the GIS are antennas installed for PD monitoring. GIS have
insulating spaces which hold the central conductor in place. However, for this project, the spaces are omitted and the
GIS is capped at either end.== GIS defects From a study of GIS in China, the most common type of defect is poor
electrical contact between segments, the second most common is particle defects, accounting for around 20% of all
failures @internalDefects. Metallic particles are free-floating in the gas insulation but can often settle on support
insulators. They can be introduced during manufacturing, created during assembly when parts are put into place or during
the operation of actuators. Larger defects such as nuts or bolts can be shed by components during operation. The least
common particle fault are protrusions from the HV conductors.

= The proposed solution
This new method can act in addition to PD detection by utilising the existing UHF antennas installed in GIS. One antenna
is used to set up a standing wave in the GIS while another is used to monitor the magnitude of the field. Defects moving
down the GIS should scatter the standing wave resulting in a changing magnitude. Recording this magnitude over the
lifetime of the installation can be used to track changes to the mechanical structure of the GIS and identify defects.

A simulation is done in EMPro and a practical experiment is done with a metal box. Two simulations are done, one to show
the electric field inside the GIS and another to replicate the practical setup with the metal box.

= Simulation
#figure(
  image("images/GISEMPro.png"),
  caption: [The GIS section modelled in EMPro showing the electric field magnitude (V/m) with the enclosure hidden.],
) <GIS1>

@GIS1 shows a simulation done in EMPro with the outer enclosure hidden. A standing wave is set up with an antenna in the
top left and recorded with an antenna in the top right.

#figure(
  image("images/defectRange.png", width: 14cm),
  caption: [A parameter sweep for a range of defect sizes showing the magnitude of the electric field (V/m) over defect position.],
) <defectRange>

@defectRange shows the maximum amplitude of the field recorded at the second antenna as a defect moves down the line for
a range of defect sizes from 5-40mm.

For comparison with= Practical Experiment The practical experiment is conducted using a $1m^3$ metal box.


= Conclusion
#lorem(150)

#bibliography("refs.bib", style: "ieee", title: "References")
