#import "template.typ": *

#show: cardiff-poster.with(
  project-title: "Microwave Mechanical Monitoring",
  author: "Archie Webster",
  author-email: "webstera2@cardiff.ac.uk",
  school: "School of Engineering, Cardiff University, Cardiff, Wales, United Kingdom",
  supervisor: "Dr Alistair Reid",
  logo: "Cardiff_University_logo.png",
)


= Introduction
Gas Insulated Switchgear (GIS) describes equipment used in power systems where components are fully enclosed in a metal housing and pressurised with an insulating gas, commonly sulphur hexafluoride. In comparison to air-insulated lines (AIS), this can significantly reduce the size of substations.

The draw back of GIS is the introduced complexity of identifying and repairing faults due to the inaccessibility of the components. The second most common fault in GIS operation is particle defects. Particles suspended in the insulating gas or adhered to the conductors can cause partial discharge (PD) to occur; a localised electrical breakdown.

Present monitoring techniques detect the ultra-high frequency (UHF) or acoustic signals generated by PD @UFHvsAcoustic, however, these techniques are reactive. The novel microwave mechanical monitoring approach discussed in this project aims to detect particles before they lead to PD.
= Structure of GIS
The GIS studied for this project are busbars, a high-voltage (HV) inner conductor surrounded by insulating gas, completely enclosed in a cylindrical metal shell @franks2022gis. Regularly spaced along the GIS are antennas installed for PD monitoring @sensorPlacement. GIS have insulating spaces which hold the central conductor in place. However, for this project, the spacers are omitted and the GIS is capped at either end.
= GIS defects
Particle defects:
- The second most common defect type
- Account for 20% of all failures @internalDefects
- Can be free-floating in the gas insulation
- Can settle on support insulators
- Can be formed from the structure (protrusions)
- Can be introduced during manufacturing
- Also created during assembly or operation when parts rub against each other

Larger defects such as nuts or bolts can be shed by components during operation. The least common particle fault are protrusions from the HV conductors.

// #linebreak()
// #linebreak()
// #linebreak()
// #linebreak()
// #linebreak()
// #linebreak()
// #linebreak()

= The proposed solution
This new method can act in addition to PD detection by utilising the existing UHF antennas installed in GIS. One antenna is used to set up a standing wave while another is used to monitor the magnitude of the field. Defects moving down the GIS should scatter the standing wave resulting in a changing magnitude. Recording this magnitude over the lifetime of the installation can be used to track changes to the mechanical structure of the GIS and identify defects.

#show heading: it => [
  #set align(center)
  #set text(blue)
  #pad(top: -0.1em, bottom: -0.8em)[#it.body]
  #line(length: if it.depth == 1 { 100% } else { 80% }, stroke: 1.5pt + blue)
]

= Simulation

== GIS simulation
#figure(
  image("images/GISEMPro.png", width: 16cm),
  caption: [The GIS section modelled in EMPro showing the electric field magnitude (V/m) with the enclosure hidden.],
) <GIS1>

@GIS1 shows a simulation done in EMPro with the outer enclosure hidden. A standing wave is set up with an antenna in the top left and recorded with an antenna in the top right.

#figure(
  image("images/defectRange.png", width: 16cm),
  caption: [A parameter sweep for a range of defect sizes showing the magnitude of the electric field (V/m) over defect position.],
) <defectRange>

@defectRange shows the maximum amplitude of the field recorded at the second antenna as a defect moves down the line for a range of defect sizes from 5-40mm. The output displays a sinusoidal nature as the defect moves through the nodes and antinodes of the standing wave.

== Metal box simulation

#figure(
  image("images/1mCubeCool.png", width: 13cm),
  caption: [A simulation of a 1m metal box, the injecting antenna is located in the top right of the box, the point sensor is located in the top left (red dot) showing the electric field magnitude (V/m).],
) <1mCubeCool>



@1mCubeCool shows the electric field inside the metal box. The mode shown is 4,4,4.

#figure(
  image("images/1mBoxSizeandPos.png", width: 15cm),
  caption: [A parameter sweep of the 1m box showing the electric field magnitude against defect position for different defect sizes.],
) <1mBoxSizeandPos>

@1mBoxSizeandPos shows a similar sinusoidal output to @defectRange as a defect is moved through the cube for a range of defect sizes.

#show heading: it => [
  #set align(center)
  #set text(red)
  #pad(top: -0.1em, bottom: -0.8em)[#it.body]
  #line(length: if it.depth == 1 { 100% } else { 80% }, stroke: 1.5pt + red)
]

= Practical Experiment
The practical experiment is conducted using a $1m^3$ metal box. Two experiments were run. In the first experiment, the defect is moved incrementally after opening the box before each measurement. In the second experiment, the defect is pulled through the box using a piece of fishing line. The second experiment records the transient effects of a moving defect.

The output of the NanoVNA shown is the insertion loss in dB, which is the S21 magnitude expressed in decibels.

#figure(
  image("images/NanoVNARec.png", width: 15cm),
  caption: [The S21 parameter against defect position recorded with the NanoVNA. ],
) <nanoVNA>

@nanoVNA shows the S21 parameter recorded with the NanoVNA against defect position. The defect is a cylinder of diameter $76.2 "mm"$ with a height of $20 "mm"$.


#figure(
  image("images/transientResponse.png", width: 15cm),
  caption: [The S21 parameter against defect position recorded with the NanoVNA for a transient response. ],
) <transientResponse>

#show heading: it => [
  #set align(center)
  #set text(orange)
  #pad(top: -0.1em, bottom: -0.8em)[#it.body]
  #line(length: if it.depth == 1 { 100% } else { 80% }, stroke: 1.5pt + orange)
]

= Conclusion
The simulations show the influence of defects on the magnitude of the standing wave and the resulting sinusoidal output. These results are shown to be similar in the metal box simulation. Practical experiments show that the NanoVNA is able to detect a large defect through the cube with the same output characteristics as the simulations.

In the simulations, the sensitivity was shown to be dependant on the particle size and how close the defects moved to the antinodes. This may potentially limit the applications of this approach for the protrusion type of defects.

This project focussed on testing a simple GIS busbar and has not simulated complex GIS structures. Future work should test more complex geometries with practical sections of GIS.



#show heading: it => [
  #set align(center)
  #set text(black, size: 29pt)
  #pad(top: -0.1em, bottom: -0.8em, left: .3em)[#it.body]
  #line(length: if it.depth == 1 { 100% } else { 80% }, stroke: 1.5pt + black)
]

#bibliography("refs.bib", style: "ieee", title: "References")
